name: flutter_background_maps_tracking
description: This package is designed for seamlessly tracking a user's movement on a Google Maps interface, even when the application is running in the background.
version: 0.0.1
homepage: https://github.com/joseflorgaston/flutter_background_maps_tracking
repository: https://github.com/joseflorgaston/flutter_background_maps_tracking

environment:
  sdk: '>=3.1.5 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  google_maps_flutter: ^2.5.0
  flutter_polyline_points: ^2.0.0
  background_location: ^0.11.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mockito: ^5.4.2
  location: ^5.0.3

flutter:
